name: Flutter_Android_DEMO

on:
  push:
    branches: [main]
    tags:
      - '*'
  pull_request:
    branches: [main]

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout

      - name: Setup Java to compile Android project
        uses: actions/setup-java
        with:
            java-version: "11"

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.9"

      - name: Create the Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
        run: |
          # import keystore from secrets
          ls -all
          echo $KEYSTORE_BASE64 | base64 -di > android/app/key.jks
          echo $KEY_PROPERTIES | base64 -di > android/key.properties

      - name: Restore packages
        run: flutter pub get

      - name: Build Android App Bundle
        run: flutter build apk --release

      # - name: Upload PGYER File
      #   uses: xtayga/upload-pgyer-action@master
      #   with:
      #     url: https://www.pgyer.com/apiv2/app/upload
      #     forms: '{"_api_key": "${{ secrets.PGY_KEY }}", "buildName": "RSSAndroid"}'
      #     file: build/app/outputs/apk/release/app-release.apk

      # - name: Publish Android Artefacts
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: release-aab
      #     path: build/app/outputs/apk/release/app-release.apk